title: Cozy Gathering Games
description: Your calm corner for feel-good games - curated cozy gaming experiences
url: "https://cozygatheringgames.xyz"
baseurl: ""

author:
  name: Cozy Gaming Team
  email: hello@cozygatheringgames.xyz

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/